# https://pnpm.io/settings

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
blockExoticSubdeps: true
dedupePeers: true
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - ocache*
  - rou3*
  - ufo*
  - h3*
trustPolicy: no-downgrade
